### PR TITLE
New keys.py for new readchar_linux (coming separately)

### PR DESCRIPTION
**Pull request by suresttexas00**

### CODE REVIEW

**Comment by suresttexas00** [comment]
Sorry to do these separately.. I did not clone a copy.

**Comment by guiweber** [comment]
Thanks, works great : )

**Comment by suresttexas00** [comment]
I hate to do this, but I kind of gave up on this package some.  I wrote a simpler, easier version that works well for my cross-platform needs (this one, sadly, does not).
Maybe check it out and see what you think?  At least it might give you ideas for this repo.

https://github.com/suresttexas00/readkey

**Comment by guiweber** [comment]
Yes, I saw that and checked the code quickly. It looks really neat! The project I needed a keystroke reader for is done, but I'll definitely try it out if I need such a module for another project.

For now I'm just trying to get this PR merged because I think it can benefit other people who end up using the module.

**Pull request merged**
